# Generated by Django 3.1.2 on 2020-11-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkbush', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='target',
            new_name='url',
        ),
    ]
